Add support for rails version 7.0
que-rb/que pull request #392
Opened 2023-04-12 21:28 UTC by kevinrobayna

Rails 7.0 was released a while ago so we should ensure we support it.

2023-04-12 21:29 UTC, kevinrobayna commented on .github/workflows/tests.yml
> +        rails_gemfile: ['6.0', '6.1', '7.0']
6.0 is reaching its end of life soon but again if it's not annoying anyone we should keep it. https://endoflife.date/rails

2023-04-13 12:03 UTC, ZimbiX requested changes
Cheers =)

This will need to be rebased once https://github.com/que-rb/que/pull/390 merges.

Again, let's update the Postgres versions tests to use the latest of everything else.

We're getting a lot of matrix permutations again (testing a version of something against every version of everything else). We don't have to address this now, but if a build starts to take too long to get through them all, we should probably move some out like with the PostgreSQL versions.

2023-04-17 04:31 UTC, oeoeaio commented
I will hold off doing a patch release until this is rebased and merged.

2023-04-27 15:53 UTC, kevinrobayna commented
Hi @ZimbiX and @oeoeaio i just rebased the branch let see what the specs say.

2023-04-28 11:24 UTC, ZimbiX approved these changes
Cheers

2023-04-28 11:24 UTC, merged